[package]
name = "development-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.3"
log = "0.4.21"
log4rs = "1.3.0"
syslog = "6.1.0"
